Fix lint error about post_notification permission
Fix following error:

Error: When targeting Android 13 or higher, posting a permission
requires holding the POST_NOTIFICATIONS permission
(usage from leakcanary.NotificationEventListener) [NotificationPermission]

   Explanation for issues of type "NotificationPermission":
   When targeting Android 13 and higher, posting permissions requires holding
   the runtime permission android.permission.POST_NOTIFICATIONS.